### ISSUE TITLE
getPowerStatus returns null

### ISSUE THREAD

**Issue by tvrulesme** [jensrossbach/node-red-contrib-sony-audio-control#1]
I am using a Sony STR-DN1080 receiver and am able to successfully use curl to query the api. 

```
curl -X POST \
  http://192.168.0.139:10000/sony/system \
  -H 'Content-Type: application/json' \
  -d '{
 "method":"getPowerStatus",
 "id":50,
 "params":[],
 "version":"1.1"
}' 
```

Which returns 
```
{
    "id": 50,
    "result": [
        {
            "status": "active"
        }
    ]
}
```

But the node-red-contrib-sony-audio-control returns null for getPowerStatus. Is it using an old version on the api which does not use service as part of the url? Looking through the code not sure how it is actually making the requests or I would help out with a pull request.

Many thanks in advance.

**Comment by jensrossbach** [comment]
Hello @tvrulesme,
can you elaborate a bit more on how your setup of node-red-contrib-sony-audio-control nodes looks like? I have tested `getPowerStatus` a lot with my Sony HT-XT3 as it was one of the first commands I implemented here. So this should work for sure and I assume that maybe the setup of the nodes is not correct in your case.

I propose to use a control node configured for "Get Power Status" and connect it with a request node. When you then trigger the control node, you should get the correct response at the result output of the request node (you can also further connect this with a filter node in order to get a result in form of true/false for the power status).

**Comment by tvrulesme** [comment]
Thanks for the quick replay @jensrossbach 

When I connect a request node as suggested this works. So the control node has no function when used on it's own or have I missed something?

**Comment by jensrossbach** [comment]
Yes, the control node cannot be used stand-alone, it always has to be connected to a request node. It is just a kind of frontend for convenience which simplifies the usage of the audio control API.

You can also use the request node without connecting to a control node. In this case you have to have some knowledge about the audio control API, i.e. you have know the service name, method name, method version and all arguments of a certain method in order to call it.

Please have a look at the README.md in the repository. There I’ve documented all the details about the different nodes.
